// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/parameter_store_interface.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ParameterStore_Store_FullMethodName     = "/parameterstore.ParameterStore/Store"
	ParameterStore_Retrieve_FullMethodName  = "/parameterstore.ParameterStore/Retrieve"
	ParameterStore_AddAccess_FullMethodName = "/parameterstore.ParameterStore/AddAccess"
)

// ParameterStoreClient is the client API for ParameterStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParameterStoreClient interface {
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error)
	AddAccess(ctx context.Context, in *AddAccessRequest, opts ...grpc.CallOption) (*AddAccessResponse, error)
}

type parameterStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewParameterStoreClient(cc grpc.ClientConnInterface) ParameterStoreClient {
	return &parameterStoreClient{cc}
}

func (c *parameterStoreClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, ParameterStore_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parameterStoreClient) Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveResponse)
	err := c.cc.Invoke(ctx, ParameterStore_Retrieve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parameterStoreClient) AddAccess(ctx context.Context, in *AddAccessRequest, opts ...grpc.CallOption) (*AddAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAccessResponse)
	err := c.cc.Invoke(ctx, ParameterStore_AddAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParameterStoreServer is the server API for ParameterStore service.
// All implementations must embed UnimplementedParameterStoreServer
// for forward compatibility.
type ParameterStoreServer interface {
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
	Retrieve(context.Context, *RetrieveRequest) (*RetrieveResponse, error)
	AddAccess(context.Context, *AddAccessRequest) (*AddAccessResponse, error)
	mustEmbedUnimplementedParameterStoreServer()
}

// UnimplementedParameterStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParameterStoreServer struct{}

func (UnimplementedParameterStoreServer) Store(context.Context, *StoreRequest) (*StoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedParameterStoreServer) Retrieve(context.Context, *RetrieveRequest) (*RetrieveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Retrieve not implemented")
}
func (UnimplementedParameterStoreServer) AddAccess(context.Context, *AddAccessRequest) (*AddAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAccess not implemented")
}
func (UnimplementedParameterStoreServer) mustEmbedUnimplementedParameterStoreServer() {}
func (UnimplementedParameterStoreServer) testEmbeddedByValue()                        {}

// UnsafeParameterStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParameterStoreServer will
// result in compilation errors.
type UnsafeParameterStoreServer interface {
	mustEmbedUnimplementedParameterStoreServer()
}

func RegisterParameterStoreServer(s grpc.ServiceRegistrar, srv ParameterStoreServer) {
	// If the following call pancis, it indicates UnimplementedParameterStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ParameterStore_ServiceDesc, srv)
}

func _ParameterStore_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParameterStoreServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParameterStore_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParameterStoreServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParameterStore_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParameterStoreServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParameterStore_Retrieve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParameterStoreServer).Retrieve(ctx, req.(*RetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParameterStore_AddAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParameterStoreServer).AddAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParameterStore_AddAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParameterStoreServer).AddAccess(ctx, req.(*AddAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParameterStore_ServiceDesc is the grpc.ServiceDesc for ParameterStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParameterStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parameterstore.ParameterStore",
	HandlerType: (*ParameterStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _ParameterStore_Store_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _ParameterStore_Retrieve_Handler,
		},
		{
			MethodName: "AddAccess",
			Handler:    _ParameterStore_AddAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/parameter_store_interface.proto",
}
